First branch
Emeljanov/hospital pull request #1
Opened 2020-12-08 08:38 UTC by Emeljanov

2020-12-09 10:02 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/Runner.java
> +        TerminalProgramm terminalProgramm = new TerminalProgramm(userDAO,patientDAO,doctorDAO,therapyDAO);
Do not forget to apply formatting to the code

2020-12-09 10:02 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgramm.java
> +    TherapyDAO therapyDAO;
make fields private
make fields final as they only initialized in constructor

2020-12-09 10:02 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgramm.java
> +        System.out.println("Hi, you are a doctor or patient? (d/p). If you are new user - create account(new)");
Let's replace all `System.out` with slf Logger

2020-12-09 10:02 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgramm.java
> +        try(BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in))) {
probably it is more convenient to use `Scanner` instead of `BufferedReader` as it performs splitting automatically

2020-12-09 10:02 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgramm.java
> +                user.setUserType(UserType.DOCTOR);
Can we set user type in constructor? We know that `GeneralDoctor()` is `UserType.DOCTOR` and `OrdinaryPatient()` is  `UserType.PATIENT`

2020-12-09 10:02 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgramm.java
> +        startProgramm();
It's better to loop in `startProgram` method rather than call it after each action

2020-12-09 10:02 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgramm.java
> +        userDAO.saveUser(user);
You need to extract such kind of logic to a separate business layer (say `UserService`). At the moment you are mixing presentation and business layers together

2020-12-09 10:02 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgramm.java
> +    private void forDoctor(BufferedReader bufferedReader, Doctor doctor) throws IOException, UserDAOException {
method name should be a verb

2020-12-09 10:02 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/model/dao/implementation/FileDoctorDAO.java
> +        return null;
It is bad practice to return `null` when something was not found. It's better to make use of `java.util.Optional`

2020-12-09 10:02 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/service/StringToList.java
> +        ArrayList<Integer> result = new ArrayList<>();
Try to refactor this method to make use of Stream API.

2020-12-10 12:50 UTC, N0TARGET requested changes

2020-12-10 12:50 UTC, N0TARGET commented on hospital/src/main/java/by/emel/anton/TerminalProgram.java
> +    private void createNewUser(Scanner scanner)  {
you can create 3 different classes with a common interface to perform all necessary logic inside.

2020-12-10 12:50 UTC, N0TARGET commented on hospital/src/main/java/by/emel/anton/TerminalProgram.java
> +    private void createNewUser(Scanner scanner)  {
for new user, doctor, patient

2020-12-10 12:50 UTC, N0TARGET commented on hospital/src/main/java/by/emel/anton/constants/Constans.java
> +public class Constans {
Constants

2020-12-10 12:50 UTC, N0TARGET commented on hospital/src/main/java/by/emel/anton/model/dao/interfaces/DoctorDAO.java
> +    void setDoctorIdToPatient(Doctor doctor, Patient patient);
I think this method is not suitable for the interface

2020-12-10 13:10 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgram.java
> +            startProgram();
This is a recursive call. You'll get `StackOverflowException` at some point. You can just make a `while` loop here. You have some other places to fix.

2020-12-10 13:10 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgram.java
> +        userService.setUserData(user,login,password,name,birthday);
User shold be created and populated here. After that it should be passed to `userService.saveUser()`
`userService.setUserData(...)` is redundant

2020-12-10 13:10 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgram.java
> +        switch (answer) {
It is always better to use enums in switch statements. Please use enum here and in similar places

2020-12-10 13:10 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/TerminalProgram.java
> +        Optional<Doctor> doctor = userService.getDoctor(login,password);
do not forget to apply code formatting.

2020-12-10 13:10 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/model/dao/implementation/FileDoctorDAO.java
>          try(BufferedReader bufferedReader = new BufferedReader(new FileReader(Constans.FILE_PATH_DOCTORS))) {
This is old-fashioned way of reading file. You can make use of `Files` utility helper and stream all lines of a file

2020-12-10 13:10 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/service/UserServiceImpl.java
> +
redundant empty line

2020-12-10 13:10 UTC, dvoryadkin1989 commented on hospital/src/main/java/by/emel/anton/service/StringToList.java
>          if(!line.equals(Constans.EMPTY)) {
why not just to check `line.isEmpty()`?

2020-12-15 09:30 UTC, merged